name: tone_web
description: "A new Flutter project."
# 아래 줄은 `flutter pub publish` 명령어로 패키지가  
# pub.dev에 실수로 배포되는 것을 방지합니다. 비공개 패키지에 권장됩니다.

publish_to: 'none' # pub.dev에 배포하려면 이 줄을 삭제하세요.

# 아래는 애플리케이션의 버전과 빌드 번호를 정의합니다.  
# 버전 번호는 점(.)으로 구분된 세 개의 숫자(예: 1.2.43)이며,  
# 선택적으로 + 뒤에 빌드 번호를 붙일 수 있습니다.  
# Flutter build 명령어에서 --build-name과 --build-number 옵션을 사용해  
# 버전과 빌드 번호를 각각 오버라이드할 수 있습니다.  
# Android에서는 build-name이 versionName으로, build-number는 versionCode로 사용됩니다.  
# Android 버전 관리에 대한 자세한 내용은 다음 링크를 참고하세요: https://developer.android.com/studio/publish/versioning  
# iOS에서는 build-name이 CFBundleShortVersionString으로,  
# build-number는 CFBundleVersion으로 사용됩니다.  
# iOS 버전 관리에 대한 자세한 내용은 다음 링크를 참고하세요:  
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html  
# Windows에서는 build-name이 제품 및 파일 버전의 주/부/수 버전으로,  
# build-number는 빌드 접미사로 사용됩니다.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

# dependencies는 이 패키지가 동작하는 데 필요한 다른 패키지들을 지정합니다.  
# 의존성을 최신 버전으로 자동 업그레이드하려면  
# `flutter pub upgrade --major-versions` 명령어를 실행해 보세요.  
# 또는 아래 버전 번호를 pub.dev에서 제공하는 최신 버전으로  
# 수동으로 수정해도 됩니다. 새 버전이 있는지 확인하려면 `flutter pub outdated`를 실행하세요.

dependencies:
  flutter:
    sdk: flutter

  # 아래 설정은 Cupertino Icons 폰트를 애플리케이션에 추가합니다.  
  # iOS 스타일 아이콘은 CupertinoIcons 클래스로 사용할 수 있습니다.

  cupertino_icons: ^1.0.8
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 아래의 "flutter_lints" 패키지는 권장하는 린트 규칙 세트를 포함하고 있어  
  # 좋은 코딩 습관을 장려합니다. 이 패키지가 제공하는 린트 세트는  
  # 프로젝트 루트의 `analysis_options.yaml` 파일에서 활성화됩니다.  
  # 특정 린트 규칙을 비활성화하거나 추가 규칙을 활성화하려면 해당 파일을 참고하세요.

  flutter_lints: ^5.0.0
# 이 파일의 일반적인 Dart 구성에 대한 정보는  
# 다음 페이지를 참고하세요: https://dart.dev/tools/pub/pubspec

# 아래 섹션은 Flutter 패키지에만 해당됩니다.

flutter:
  fonts:
      - family: NotoSansKR
        fonts:
          - asset: assets/fonts/NotoSansKR-VariableFont_wght.ttf
      - family: NotoSansJP
        fonts:
          - asset: assets/fonts/NotoSansJP-VariableFont_wght.ttf
  # 아래 줄은 Material Icons 폰트가  
  # 애플리케이션에 포함되도록 해주며,  
  # material Icons 클래스의 아이콘들을 사용할 수 있게 합니다.

  uses-material-design: true
  # 애플리케이션에 에셋을 추가하려면, 아래와 같이 assets 섹션을 추가하세요:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 이미지 에셋은 해상도에 따라 달라지는 "변형(variant)"을 참조할 수 있습니다.
  # 자세한 내용은 다음을 참고하세요:
  # https://flutter.dev/to/resolution-aware-images

  # 패키지 의존성에서 에셋을 추가하는 방법에 대한 자세한 내용은 아래를 참고하세요:
  # https://flutter.dev/to/asset-from-package

  # 애플리케이션에 사용자 지정 폰트를 추가하려면, 이 "flutter" 섹션 안에
  # fonts 섹션을 추가하세요. 이 리스트의 각 항목은 폰트 패밀리 이름을 나타내는
  # "family" 키와, 해당 폰트에 대한 에셋과 속성들을 포함하는 "fonts" 키를 가져야 합니다.
  # 예시는 다음과 같습니다:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 패키지 의존성에서 폰트를 사용하는 방법은 아래 문서를 참고하세요:
  # https://flutter.dev/to/font-from-package
